pages:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'  
  script:
    - pip install sphinx
    - sphinx-build source public
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - scp -r public/* texta-docs@web.texta.ee:/opt/docs/
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
  - pages

