version: '3'

# NOTE: This is an example setup. This is NOT a production-ready solution!

services:

  texta-elasticsearch:
    container_name: texta-elasticsearch
    restart: on-failure
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
    ports:
      - 9200
    environment:
     - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  texta-redis:
    container_name: texta-redis
    image: redis
    restart: on-failure
    ports:
    - 6379

  texta-mariadb:
    container_name: texta-mariadb
    image: mariadb:10.3.28
    restart: on-failure
    ports:
      - 3306
    environment:
      MYSQL_ROOT_USER: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_PORT: 3306
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mariadb-data:/var/lib/mysql

  texta-rest:
    container_name: texta-rest
    image: docker.texta.ee/texta/texta-rest:latest
    ports:
      - 80:80
    env_file:
      - ./env
    volumes:
      - toolkit-data:/var/texta-rest/data
    depends_on:
      - texta-mariadb
      - texta-elasticsearch
      - texta-redis

volumes:
  elastic-data:
  toolkit-data:
  mariadb-data:
